server:
  port: 8090
---
spring:
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway GlobalFilter
            preLogger: true
            postLogger: true
      routes:
        - id: user
          uri: http://localhost:8000/
          predicates:
            - Path=/api/user/**
          filters:
            - name: UserFilter
              args:
                baseMessage: Spring Cloud Gateway UserFilter
                preLogger: true
                postLogger: true
        - id: news
          uri: http://localhost:8001/
          predicates:
            - Path=/api/news/**
          filters:
            - name: NewsFilter
              args:
                baseMessage: Spring Cloud Gateway NewsFilter
                preLogger: true
                postLogger: true
        - id: review
          uri: http://localhost:8002/
          predicates:
            - Path=/api/review/**
          filters:
            - name: ReviewFilter
              args:
                baseMessage: Spring Cloud Gateway ReviewFilter
                preLogger: true
                postLogger: true
        - id: advertising
          uri: http://localhost:8003/
          predicates:
            - Path=/api/advertising/**
          filters:
            - name: AdvertisingFilter
              args:
                baseMessage: Spring Cloud Gateway AdvertisingFilter
                preLogger: true
                postLogger: true